#pragma config(Sensor, S1,     RightSonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     RightColor,     sensorEV3_Color)
#pragma config(Sensor, S3,     LeftColor,      sensorEV3_Color)
#pragma config(Sensor, S4,     LeftSonic,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	long file;
	short maxLeft = 0, minLeft = 101, maxRight = 0, minRight = 101;
	//file = fileOpenWrite("file");
	file =fileOpenWrite("file");
	while (nMotorEncoder[leftMotor] < 1000)
	{
		motor[leftMotor] = 20;
		motor[rightMotor] = 20;
		int left = SensorValue[LeftColor];
		int right = SensorValue[RightColor];
		if (left > maxLeft) maxLeft = left;
		if (right > maxRight) maxRight = right;
		if (left < minLeft) minLeft = left;
		if (right < minRight) minRight = right;
	}
	fileWriteFloat(file, maxLeft);
	fileWriteFloat(file, minLeft);
	fileWriteFloat(file, maxRight);
	fileWriteFloat(file, minRight);

	fileClose(file);

	file = fileOpenRead("file");
	float  a = 0, b = 0, c = 0, d = 0;
	fileReadFloat(file, &a);
	displayString(3, "%d", a);

	fileReadFloat(file, &b);
	displayString(4, "%d", b);

	fileReadFloat(file, &c);
	displayString(5, "%d", c);

	fileReadFloat(file, &d);
	displayString(6, "%d", d);
	motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		fileClose(file);
	while (true) {}
}
