
#pragma config(Sensor, S1,     RightSonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     RightColor,     sensorEV3_Color)
#pragma config(Sensor, S3,     LeftColor,      sensorEV3_Color)
#pragma config(Sensor, S4,     LeftSonic,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int SR,SL,speed1,speed2;

void GoForward()
{
	speed1 = 50;
	speed2 = 50;
}
void TurnRight()
{
	speed1 = 15;
	speed2 = 80;
}
void TurnLeft()
{
	speed1 = 80;
	speed2 = 15;
}
void line()
{
		if ((SensorValue[LeftColor] > SL) && (SensorValue[RightColor] > SR)) GoForward();
		if (SensorValue[RightColor] < SR) TurnRight();
		if (SensorValue[LeftColor] < SL) TurnLeft();
}
void GoToCross
{
	while (nMotorEncoder[leftMotor] = 1260) GoForward;
}

task Sensor
{
		long file = 0;
		float maxLeft = 0, maxRight = 0, minLeft = 0, minRight = 0;
		file = fileOpenRead("file");
		fileReadFloat(file, &maxLeft);
		fileReadFloat(file, &minLeft);
		fileReadFloat(file, &maxRight);
		fileReadFloat(file, &minRight);
		fileClose(file);
	/*	displayString(3, "%d", maxLeft);
		displayString(4, "%d", minLeft);
		displayString(5, "%d", maxRight);
		displayString(6, "%d", minRight);*/
		(int) SR = (100 * (SensorValue[RightColor] - minRight)) / (maxRight - minRight);
		(int) SL = (100 * (SensorValue[LeftColor] - minLeft)) / (maxLeft - minLeft);

		if (SR > maxRight)
			{
				minRight = (SR * minRight) / maxRight;
				maxRight = SR;
			}
		if (SL > maxLeft)
			{
				minLeft = (SL * minLeft) / maxLeft;
				maxLeft = SL;
			}
		if (SR < minRight) maxRight = (SR * maxRight) / minRight;
		if (SL < minLeft) maxLeft = (SL * maxLeft) / minLeft;
}

task motors
{
	delay(100);
	motor[leftMotor] = speed1;
	motor[rightMotor] = speed2;
}

task main()
{
  startTask(Sensor);
  startTask(motors);
	int count = 0;
	while (true)
	{
		GoToCross();
	}
}
