#pragma config(Sensor, S1,     RightSonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     RightColor,     sensorEV3_Color)
#pragma config(Sensor, S3,     LeftColor,      sensorEV3_Color)
#pragma config(Sensor, S4,     LeftSonic,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void GoForward()
{
	motor[leftMotor] = 50;
	motor[rightMotor] = 50;
}
void TurnRight()
{
	motor[leftMotor] = 15;
	motor[rightMotor] = 80;
}
void TurnLeft()
{
	motor[leftMotor] = 80;
	motor[rightMotor] = 15;
}
task main()
{
	while (true)
	{
		if ((SensorValue[LeftColor] > 42) && (SensorValue[RightColor] > 42)) GoForward();
		if (SensorValue[RightColor] < 42) TurnRight();
		if (SensorValue[LeftColor] < 42) TurnLeft();
	//	if ((SensorValue[LeftColor] < 42) && (SensorValue[RightColor] < 42))
	}
}
